insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (1004,'ALTERACAO SITUACAO DA LIGACAO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (10,'TRANSFERENCIA DE CONSUMIDOR');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (110,'LOCALIZAR IMOVEL');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (1185,'ATUALIZACAO CADASTRAL GSAN');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (11,'EXCLUSAO DE CONTAS');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (12,'CREDITO POR PAG. DE CONTA EM DUPLICIDADE E OUTROS');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (13,'EXTRATO DE 2 VIA DE CONTA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (14,'EXCLUSAO DE JUROS E MULTA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (151,'RELIGACAO-INTERIOR');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (15,'INCLUSAO DE DEBITO AUTOMATICO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (16,'EXCLUSAO DE DEBITO AUTOMATICO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (17,'PROBLEMAS COM DE DEBITO AUTOMATICO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (18,'VAZAMENTO NA REDE (RUA)');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (19,'MATERIAL DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (1,'LIGACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (20,'MATERIAL DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (21,'REQUERIMENTOS');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (22,'SERVICOS (ESGOTO)');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (23,'HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (24,'CADASTRO DE CONSUMIDOR');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (252,'CONFIRMAR DADOS CORTE LIGACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (253,'CONFIRMAR DADOS SUPRESSAO LIGACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (254,'CONFIRMAR DADOS  LIGACAO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (255,'CONFIRMAR DADOS LIGACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (25,'REPOSICAO DE CALCAMENTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (26,'ALTERACAO DO VENCIMENTO DA FATURA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (27,'REVISAO DE LEITURA E/OU CONSUMO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (28,'FALTA DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (29,'REVISAO DE TARIFAS (ECONOMIA)');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (2,'LIGACAO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (307,'RETIRADA DE HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (30,'DESENTUPIMENTO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (313,'CONFIRMAR DADOS INSTALACAO DE HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (314,'CONFIRMAR DADOS SUBSTITUICAO DE HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (31,'DETALHAMENTO DE DEBITO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3231,'FORNECIMENTO CARRO PIPA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3232,'VERIFICAR INSTALACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3233,'DESLIGAMENTO RAMAL DE AGUA/ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3234,'DIAGNOSTICO DE DESMEMBRAMENTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3236,'LEVANTAMENTO GERAL DO IMOVEL');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3237,'FISCALIZACAO DE LEITURA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3238,'MANUTENCAO DE CAVALETE');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3239,'INTERVENCAO NAS INSTALACOES DOS SERVICOS PUBLICOS');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3240,'LIGACOES CLANDESTINAS');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3241,'VIOLACAO OU RETIRADA DE HIDROMETROS OU LIMITADOR D');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3242,'INTERCONEXAO DA INST. PREDIAL COM CANALIZACOES DE');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3243,'UTILIZACAO DA LIGACAO DE AGUA OU ESGOTO PARA SERVE');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3244,'LANCAMENTO DE AGUAS PLUVIAIS NA INSTALACAO DE ESGO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3245,'LIGACOES DE BOMBAS OU EJETORES NA REDE DISTRIBUIDO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3246,'LANCAMENTO DE DESPEJOS NA REDE COLETORA QUE EXIJAM');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3250,'INICIO DE OBRAS DE INSTALACAO DE AGUA E /OU ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3251,'ALTERACAO DE PROJETO DE INSTALACAO DE AGUA E/OU ES');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3252,'INSTALACAO DE TORNEIRAS ANTES DO HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3253,'INVERSAO DO HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3254,'LIGACAO DE ESGOTOS SEM CAIXA DE GORDURA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (32,'HISTORICO DE LEITURA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (33,'FALTA DAGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (34,'PROBL. NO FORNECIMENTO - AGUA FRACA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (35,'VERIFICAR CORTE');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (36,'INSTALACAO DE HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (37,'INSTALACAO DE HIDROMETRO (NOVO)');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (38,'CONTROLE ETA/CAP');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (39,'NAO RECEBIMENTO DE CONTA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (3,'CORTE POR ATRASO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (40,'VERIFICAR CADASTRO EM DUPLICIDADE');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (41,'SETOR DE CADASTRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (42,'SUBSTITUICAO DE RAMAL');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (43,'SUBSTITUIR A TAMPA DO HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (44,'RETIRADA DE MULTA E JUROS');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (45,'CONTAS PAGAS CIDADE');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (46,'SETOR DE MEDICAO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (47,'SETOR DE CADASTRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (48,'SETOR DE FATURAMENTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (49,'OUTROS TIPOS DE SERVICOS - IDENTIFICAR');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (4,'RELIGACAO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (50,'FAZER LEVANTAMENTO GERAL DA RESIDENCIA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (51,'PESQUISA DE VAZAMENTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (52,'CORTE SUSPEITA DE GATO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (53,'INTERVENCAO  NO RAMAL');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (54,'PARCELAMENTO - ACERTO DE PARCELA EM ABERTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (55,'LIGACAO DE AGUA C/INSTL. HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (56,'DIAGNOSTICO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (57,'SUPRESSAO DA LIGACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (58,'RESTABELECIMENTO DA LIGACAO DE AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (5,'VERIFICAR VAZAMENTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (690,'INFORMAR CONSUMO MINIMO AGUA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (6,'SUBSTITUIR HIDROMETRO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (743,'TAMPONAMENTO DA LIGACAO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (752,'DESATIVACAO DA LIGACAO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (753,'RESTABELECIMENTO DA LIGACAO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (754,'REATIVACAO DA LIGACAO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (755,'INFORMAR VOLUME MINIMO DE ESGOTO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (7,'PARCELAMENTO DE DEBITO');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (8,'REFATURAMENTO DA CONTA');
insert into mos_servico_tipo(svtp_id, svtp_dsservicotipo) values (9,'CORTE A PEDIDO');
