-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2018-07-01 20:20:39 AMT
--   site:      Oracle9i
--   type:      Oracle9i
CREATE TABLE mos_checklist (
    chkl_id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    chkl_dtmovimento          TIMESTAMP WITHOUT TIME ZONE,
    chkl_dstipoveiculo        VARCHAR(60),
    chkl_nnmatricula          INTEGER,
    chkl_nmcondutor           VARCHAR(60),
    chkl_nmsetor              VARCHAR(60),
    chkl_dtsaida              TIMESTAMP WITHOUT TIME ZONE,
    chkl_nnkmsaida            FLOAT,
    chkl_dtretorno            TIMESTAMP WITHOUT TIME ZONE,
    chkl_nnkmretorno          FLOAT,
    chkl_nnplacaveiculo       VARCHAR(20),
    chkl_icfinalizousaida     SMALLINT,
    chkl_icfinalizouretorno   SMALLINT,
    chkl_nncnh                VARCHAR(20),
    mos_veiculo_veic_id       INTEGER NOT NULL
);

CREATE TABLE mos_checklist_grupo (
    chgr_id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    chgr_dschecklistgrupo   VARCHAR(60)
);

CREATE TABLE mos_checklist_item (
    chit_id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    chgr_id                INTEGER NOT NULL,
    chit_dschecklistitem   VARCHAR(60)
);

CREATE TABLE mos_checklist_item_opcao (
    chio_id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    chit_id                     INTEGER NOT NULL,
    chio_dschecklistitemopcao   VARCHAR(60)
);

CREATE TABLE mos_checklist_resposta (
    chre_id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    chre_dtmovimento        TIMESTAMP WITHOUT TIME ZONE,
    chre_nnplacaveiculo     VARCHAR(20),
    chre_tmsaida            TIMESTAMP WITHOUT TIME ZONE,
    chre_tmretorno          VARCHAR(10),
    chio_idsaida            INTEGER NOT NULL,
    chio_idretorno          INTEGER NOT NULL,
    mos_checklist_chkl_id   INTEGER NOT NULL
);

CREATE TABLE mos_corte_tipo (
    cotp_id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id            INTEGER NOT NULL,
    cotp_dscortetipo   VARCHAR(60)
);

CREATE TABLE mos_empresa (
    empr_id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_nmrazaosocial   VARCHAR(60),
    empr_nmfantasia      VARCHAR(60),
    empr_dsendereco      VARCHAR(60),
    empr_dscomplemento   VARCHAR(60),
    empr_nmbairro        VARCHAR(30),
    empr_nmcidade        VARCHAR(30),
    empr_coduf           VARCHAR(2),
    empr_codcep          VARCHAR(11),
    empr_nncnpj          VARCHAR(20),
    empr_nntelefone      VARCHAR(20),
    empr_dsemail         VARCHAR(100)
);

CREATE TABLE mos_equipe (
    eqpe_id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                     INTEGER NOT NULL,
    eqpe_nmequipe               VARCHAR(60),
    eqpe_nnplacaveiculo         VARCHAR(20),
    eqpe_cargahorariotrabalho   SMALLINT
);

CREATE TABLE mos_equipe_componentes (
    eqpc_id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    eqpe_id              INTEGER NOT NULL,
    func_id              INTEGER NOT NULL,
    eqpc_icresponsavel   VARCHAR(1)
);

CREATE TABLE mos_funcionario (
    func_id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id              INTEGER NOT NULL,
    func_nnmatricula     INTEGER,
    func_nmfuncionario   VARCHAR(60),
    func_nncnh           VARCHAR(20)
);


CREATE TABLE mos_hidrometro_local_armaz (
    hdla_id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                   INTEGER NOT NULL,
    hdla_dslocalarmazenagem   VARCHAR(60)
);

CREATE TABLE mos_hidrometro_local_inst (
    hloi_id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                  INTEGER NOT NULL,
    hloi_dslocalinstalacao   VARCHAR(60)
);

CREATE TABLE mos_hidrometro_protecao (
    hpro_id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id           INTEGER NOT NULL,
    hpro_dsprotecao   VARCHAR(60)
);


CREATE TABLE mos_hidrometro_situacao (
    hdst_id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                 INTEGER NOT NULL,
    hdst_dstiposituacaohm   VARCHAR(60)
);

CREATE TABLE mos_hidrometro_tipo_instal (
    htpi_id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                   INTEGER NOT NULL,
    htpi_dstipoinstalacaohm   VARCHAR(60)
);

CREATE TABLE mos_hidrometro_tipo_subs (
    hits_id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                   INTEGER NOT NULL,
    hits_dstiposubstituicao   VARCHAR(60)
);

CREATE TABLE mos_imovel (
    imov_id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                      INTEGER NOT NULL,
    legs_id                      INTEGER NOT NULL,
    lags_id                      INTEGER NOT NULL,
    imov_nninscricao             VARCHAR(30),
    imov_nmclienteresponsavel    VARCHAR(60),
    imov_nmclienteusuario        VARCHAR(60),
    imov_nmclienteproprietario   VARCHAR(60),
    imov_nncortes                INTEGER,
    imov_nnsupressoes            INTEGER,
    imov_nnreparcelamentos       INTEGER,
    imov_nndiavencimento         INTEGER,
    imov_icsituacaocobranca      SMALLINT,
    imov_icsituacaofaturamento   SMALLINT,
    imov_nnrota                  SMALLINT,
    imov_nnsequenciarota         SMALLINT,
    imov_dtligacao               TIMESTAMP WITHOUT TIME ZONE,
    imov_nnhidrometro            VARCHAR(20),
    imov_dtinstalacaohm          TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE mos_interrupcao (
    inte_id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    inmo_id                    INTEGER NOT NULL,
    empr_id                    INTEGER NOT NULL,
    eqpe_id                    INTEGER NOT NULL,
    inte_dtmovimento           TIMESTAMP WITHOUT TIME ZONE,
    inte_nmequipe              VARCHAR(60),
    inte_nnmatricula           INTEGER,
    inte_nnos                  INTEGER,
    inte_dsinterrupcaomotivo   VARCHAR(60),
    inte_dsobervacaoinicio     VARCHAR(400),
    inte_dsobervacaofim        VARCHAR(400),
    inte_dtinicio              DATE,
    inte_hrinicio              VARCHAR(10),
    inte_dtfim                 DATE,
    inte_hrfim                 VARCHAR(10),
    inte_icenviousmsinicio     SMALLINT,
    inte_icenviousmsfim        SMALLINT
);

CREATE TABLE mos_interrupcao_motivo (
    inmo_id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                    INTEGER NOT NULL,
    inmo_dsinterrupcaomotivo   VARCHAR(60),
    inmo_dsabreviado           VARCHAR(5),
    inmo_icenviarsmsinicio     SMALLINT,
    inmo_icenviarsmsfim        SMALLINT,
    inmo_icinicioatividade     SMALLINT,
    inmo_icchecklistsaida      SMALLINT,
    inmo_icchecklistretorno    SMALLINT,
    inmo_icsolicitakminicio    SMALLINT,
    inmo_iccsolicitakmfim      SMALLINT
);

CREATE TABLE mos_ligacao_agua_situacao (
    lags_id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                      INTEGER NOT NULL,
    lags_dsligacaosituacaoagua   VARCHAR(60)
);

CREATE TABLE mos_ligacao_esgoto_situacao (
    legs_id                        BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                        INTEGER NOT NULL,
    legs_dsligacaoesgotosituacao   VARCHAR(60)
)

CREATE TABLE mos_local_ocorrencia (
    loco_id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                  INTEGER NOT NULL,
    loco_dslocalocorrencia   VARCHAR(60)
);

CREATE TABLE mos_material (
    mate_id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id           INTEGER NOT NULL,
    mate_dsmaterial   VARCHAR(60),
    unid_id           INTEGER NOT NULL,
    mate_dsunidade    VARCHAR(60)
);

CREATE TABLE mos_motivo_corte (
    mcor_id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id              INTEGER NOT NULL,
    mcor_dsmotivocorte   VARCHAR(60)
);

CREATE TABLE mos_motivo_encerramento (
    mote_id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    mote_dsmotivoencerramento   VARCHAR(60)
);


CREATE TABLE mos_ordem_servico (
    orse_id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                       INTEGER NOT NULL,
    orse_cdsituacao               INTEGER,
    orse_dssituacao               VARCHAR(25),
    orse_tmgeracao                TIMESTAMP WITHOUT TIME ZONE,
    orse_dsobservacao             VARCHAR(400),
    rgat_id                       INTEGER,
    rgat_cdsituacao               INTEGER,
    rgat_dssituacao               VARCHAR(25),
    rgat_tmregistroatendimento    TIMESTAMP WITHOUT TIME ZONE,
    rgat_dsobservacao             VARCHAR(400),
    svtp_id                       INTEGER NOT NULL,
    logr_nmlogradouro             VARCHAR(60),
    bair_nmbairro                 VARCHAR(60),
    rgat_nnimovel                 VARCHAR(20),
    clie_id                       INTEGER,
    imov_id                       INTEGER,
    clie_nmcliente                VARCHAR(60),
    svtp_idexecutado              INTEGER NOT NULL,
    orse_tmencerramento           TIMESTAMP WITHOUT TIME ZONE,
    mote_id                       INTEGER NOT NULL,
    orse_dsparecerencerramento    VARCHAR(400),
    orse_dtexecucao               NUMBER,
    orse_tmexecucao_inicio        VARCHAR(10),
    orse_tmexecucao_fim           VARCHAR(10),
    eqpe_idexecucao               INTEGER NOT NULL,
    orse_nnprofunidaderede        VARCHAR(25),
    orse_nnpressaorede            VARCHAR(25),
    orse_tmcancelamento           TIMESTAMP WITHOUT TIME ZONE,
    svtp_idgerar                  INTEGER NOT NULL,
    orse_nnkminicial              INTEGER,
    orse_nnkmfinal                INTEGER,
    orse_dtprogramacao            TIMESTAMP WITHOUT TIME ZONE,
    eqpe_idprogramada             INTEGER NOT NULL,
    hidr_nnanofabricacao          INTERVAL DAY(9) TO SECOND(0),
    hidr_nnhidrometro             VARCHAR(20),
    rgat_dscomplementoendereco    VARCHAR(60),
    hidi_dtinstalacaohidrometro   TIMESTAMP WITHOUT TIME ZONE,
    hidi_nnselo                   VARCHAR(20),
    imov_nnlote                   INTEGER,
    qdra_nnquadra                 VARCHAR(10),
    imov_nnsequencialrota         INTEGER,
    imov_nnsublote                INTEGER,
    stcm_id                       INTEGER
);

CREATE TABLE mos_ordem_servico_corte (
    osco_id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id               INTEGER NOT NULL,
    mcor_id               INTEGER NOT NULL,
    cotp_id               INTEGER NOT NULL,
    func_id               INTEGER NOT NULL,
    osco_dtcorte          TIMESTAMP WITHOUT TIME ZONE,
    osco_tmcorte          VARCHAR(10),
    osco_nnleituracorte   INTEGER,
    osco_nnselocorte      VARCHAR(20)
);

CREATE TABLE mos_ordem_servico_foto (
    osft_id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id            INTEGER NOT NULL,
    osft_nmfoto        VARCHAR(60),
    osft_dsfoto        VARCHAR(60),
    osft_nnlatitude    VARCHAR(25),
    osft_nnlongitude   VARCHAR(25),
    osft_dtfoto        TIMESTAMP WITHOUT TIME ZONE,
    osft_fttipo        SMALLINT,
    osft_foto          BLOB
);

CREATE TABLE mos_ordem_servico_insthm (
    osih_id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id                    INTEGER NOT NULL,
    hloi_id                    INTEGER NOT NULL,
    hpro_id                    INTEGER NOT NULL,
    htpi_id                    INTEGER NOT NULL,
    osih_dtinstalacao          TIMESTAMP WITHOUT TIME ZONE,
    osih_ictipoprotecao        VARCHAR(1),
    osih_ictrocaprotecao       SMALLINT,
    osih_ictrocaregistro       SMALLINT,
    osih_nnleiturainstalacao   INTEGER,
    osih_nnselo                VARCHAR(20),
    osih_iccavalete            VARCHAR(1)
);

CREATE TABLE mos_ordem_servico_material (
    osmu_id             BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id             INTEGER NOT NULL,
    mate_id             INTEGER NOT NULL,
    mate_dsmaterial     VARCHAR(60),
    unid_id             INTEGER NOT NULL,
    unid_dsunidade      VARCHAR(60),
    osmu_nnquantidade   FLOAT
);

CREATE TABLE mos_ordem_servico_religacao (
    osre_id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id                   INTEGER NOT NULL,
    osre_dtreligacao          TIMESTAMP WITHOUT TIME ZONE,
    osre_tmreligacao          VARCHAR(10),
    osre_nnhidrometro         VARCHAR(20),
    osre_dtinstalacao         TIMESTAMP WITHOUT TIME ZONE,
    osre_nneiturainstalacao   INTEGER,
    osre_nnselo               VARCHAR(20),
    osre_iccavelete           VARCHAR(1),
    osre_ictrocaprotecao      SMALLINT,
    osre_ictrocaregistro      SMALLINT,
    hloi_id                   INTEGER NOT NULL,
    hpro_id                   INTEGER NOT NULL,
    retp_id                   INTEGER NOT NULL
);

CREATE TABLE mos_ordem_servico_subshm (
    ossh_id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id                    INTEGER NOT NULL,
    ossh_nnhidrometroatual     VARCHAR(20),
    ossh_ictipomedicaoatual    SMALLINT,
    ossh_dtretirada            TIMESTAMP WITHOUT TIME ZONE,
    ossh_nnleituraretirada     INTEGER,
    hdst_id                    INTEGER NOT NULL,
    hdla_id                    INTEGER NOT NULL,
    ossh_nnhidrometronovo      VARCHAR(20),
    ossh_dtinstalacao          TIMESTAMP WITHOUT TIME ZONE,
    ossh_ictipomedicao         SMALLINT,
    hloi_id                    INTEGER NOT NULL,
    hpro_id                    INTEGER NOT NULL,
    ossh_ictrocaprotecao       SMALLINT,
    ossh_ictrocaregistro       SMALLINT,
    ossh_nnleiturainstalacao   INTEGER,
    ossh_nnselo                VARCHAR(20),
    ossh_iccavalete            VARCHAR(1),
    hits_id                    INTEGER NOT NULL,
    ossh_tminstalacao          VARCHAR(10)
);

CREATE TABLE mos_ordem_servico_vala (
    osva_id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    orse_id               INTEGER NOT NULL,
    loco_id               INTEGER NOT NULL,
    pavt_id               INTEGER NOT NULL,
    osva_nnvala           SMALLINT,
    osva_nncomprimento    FLOAT,
    osva_nnlargura        FLOAT,
    osva_nnprofundidade   FLOAT,
    osva_icaterro         SMALLINT,
    osva_icentulho        SMALLINT,
    osva_nnbags           SMALLINT
);

CREATE TABLE mos_pavimento_tipo (
    pavt_id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                INTEGER NOT NULL,
    pavt_dspavimentotipo   VARCHAR(60)
);

CREATE TABLE mos_religacao_tipo (
    retp_id                INTEGER NOT NULL,
    empr_id                INTEGER NOT NULL,
    rept_dsreligacaotipo   VARCHAR(60)
);

CREATE TABLE mos_servico_tipo (
    svtp_id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    svtp_dsservicotipo   VARCHAR(60)
);

CREATE TABLE mos_servico_tipo_especificacao (
    step_id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    svtp_id                  INTEGER NOT NULL,
    step_dssolicitacaotipo   VARCHAR(60)
);

CREATE TABLE mos_unidade_medida (
    unid_id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id          INTEGER NOT NULL,
    unid_dsunidade   VARCHAR(60)
);

CREATE TABLE mos_veiculo (
    veic_id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    vemr_id                 INTEGER NOT NULL,
    vemo_id                 INTEGER NOT NULL,
    vetp_id                 INTEGER NOT NULL,
    empr_id                 INTEGER NOT NULL,
    veic_nnplaca            VARCHAR(20),
    veic_nnkmacumulada      FLOAT,
    veic_dtultimarevisao    TIMESTAMP WITHOUT TIME ZONE,
    veic_dtproximarevisao   TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE mos_veiculo_marca (
    vemr_id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id               INTEGER NOT NULL,
    vemr_dsveiculomarca   VARCHAR(60)
);

CREATE TABLE mos_veiculo_modelo (
    vemo_id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id                INTEGER NOT NULL,
    vemo_dsveiculomodelo   VARCHAR(60)
);

CREATE TABLE mos_veiculo_tipo (
    vetp_id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    empr_id              INTEGER NOT NULL,
    vetp_dsveiculotipo   VARCHAR(60)
);
